services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: travis
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      volumes: db:data/postgres
    ports:
      - 5332:5432
    expose:
      - 5332
    networks:
      - db-network
    restart: unless-stopped

networks:
  db-network:
    driver: bridge